## Global Variabel
@BaseUrl = https://pam-2026-p4-ifs23001-be.ifs23001.fun:8080/
#@BaseUrl = http://127.0.0.1:8000

## Profile
## ===========================================

## Plantspc (Komponen PC)
## ===========================================

### Mengambil semua data komponen PC
# @name getAllPlantspc
GET {{BaseUrl}}/plantspc?search=
Content-Type: application/json

### Menambahkan data komponen PC baru
# @name PostPlantspc
POST {{BaseUrl}}/plantspc
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

NVIDIA RTX 4099
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Kartu grafis kelas atas untuk performa gaming 4K terbaik dan AI
--WebAppBoundary
Content-Disposition: form-data; name="harga"

30000000
--WebAppBoundary
Content-Disposition: form-data; name="pengaruh"

Meningkatkan FPS secara drastis pada resolusi tinggi
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="me.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("plantIdpc", response.body.data.plantId);
    console.log("ID PC Baru: " + client.global.get("plantIdpc"))
%}

### Mengambil data komponen PC berdasarkan id-nya
# @name getPlantpcById
GET {{BaseUrl}}/plantspc/{{plantIdpc}}
Content-Type: application/json

### Mengubah hanya data PC (tanpa gambar baru)
# @name PutPlantpcOnlyData
PUT {{BaseUrl}}/plantspc/{{plantIdpc}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

NVIDIA RTX 4090 Super
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Update: Versi Super dengan clock speed lebih tinggi
--WebAppBoundary
Content-Disposition: form-data; name="harga"

32000000
--WebAppBoundary
Content-Disposition: form-data; name="pengaruh"

Performa lebih stabil dan suhu lebih terjaga
--WebAppBoundary--

### Mengubah gambar dan data PC
# @name PutPlantpcWithImage
PUT {{BaseUrl}}/plantspc/{{plantIdpc}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

NVIDIA RTX 4090 Pro
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Deskripsi diperbarui beserta gambar produk terbaru
--WebAppBoundary
Content-Disposition: form-data; name="harga"

35000000
--WebAppBoundary
Content-Disposition: form-data; name="pengaruh"

Optimal untuk workstation
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="gpu_updated.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

### Menghapus data PC berdasarkan id-nya
# @name deletePlantpc
DELETE {{BaseUrl}}/plantspc/{{plantIdpc}}
Content-Type: application/json